import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import NavBar from "@/components/NavBar";
import AboutMe from "@/components/AboutMe";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
  weight: "800",
  style: "italic",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sujita Pandey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ` }>
        <NavBar/>
        {children}
        <AboutMe/>
      </body>
    </html>
  );
}

